project:
  type: website
  resources: static

website:
  title: "Positive Definite Ecology"
  navbar:
    right:
      - text: Posts
        href: posts.qmd
      - icon: github
        href: https://github.com/jkbest2
      - icon: twitter
        href: https://twitter.com/isposdef
format:
  html:
    theme: darkly
    css: styles.css



